name: Deploy

on: push

env:
  SERVER_HOST: 209.38.96.160

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.NEW_SECRET_KEY }}
          script: |
            whoami
            ls -lah     
