name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SERVER_FILED_KEY }}
          script: |
            echo "wingsfit2093896160" | sudo -S sudo su
            cd /var/www/frontend
            git pull
            npm run build
            cp -r dist/* /var/www/html
            cd /var/www/backend
            git pull
            pm2 restart all