name: Deploy

on: push

env:
  SERVER_HOST: 209.38.96.160

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.NEW_SECRET_KEY }}

      - name: Deploy to Server
        run: ssh toktobekov@209.38.96.160 && ls