name: Tests

on: push

env: 
  SERVER_HOST: 209.38.96.160
  
jobs: 
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test install dependecies
        run: cd tests/ && npm ci
      - name: Test run
        run: | 
          cd tests/ && npx codeceptjs run --verbose --override '{"helpers": {"Puppeteer": {"show": false}}}' --steps
      - uses: actions/upload-artifact@v4
        if: ${{always()}}
        with:
          name: my-artifact
          path: /home/runner/work/wingsfit-frontend/wingsfit-frontend/tests/output/

      
