name: Tests

on: push

env: 
  SERVER_HOST: 209.38.96.160
  
jobs: 
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test install dependecies
        run: cd tests/ && npm ci
      - name: Test run
        run: pwd; npm run codeceptjs

      
